apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: postgres-harbor-connection
  namespace: smol-devtools
spec:
  forceRegenerate: false
  fields:
    - fieldName: password
      encoding: base64url
      length: "32"
