apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: harbor
  namespace: default
spec:
  interval: 5m
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: default
spec:
  releaseName: harbor
  targetNamespace: smol-system
  chart:
    spec:
      chart: harbor
      version: ">=1.8.0 <1.9.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
  values:
    persistence:
      persistentVolumeClaim:
        registry:
          size: 64Gi
    externalURL: https://harbor.k8s.lan
    expose:
      ingress:
        hosts:
          core: harbor.k8s.lan
          notary: notary.harbor.k8s.lan
    core:
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    chartmuseum:
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    jobservice:
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    notary:
      server:
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      signer:
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
    portal:
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    registry:
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    trivy:
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    database:
      type: internal
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
    redis:
      type: internal
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
  interval: 1m
  install:
    remediation:
      retries: 3
