apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: harbor
  namespace: default
spec:
  interval: 5m
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: default
spec:
  releaseName: harbor
  targetNamespace: smol-system
  chart:
    spec:
      chart: harbor
      version: ">=1.8.0 <1.9.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
  values:
    persistence:
      persistentVolumeClaim:
        chartmuseum:
          existingClaim: "harbor-chartmuseum-rwx"
        jobservice:
          existingClaim: "harbor-jobservice-rwx"
        registry:
          existingClaim: "harbor-registry-rwx"
    externalURL: https://harbor.k8s.lan
    expose:
      ingress:
        hosts:
          core: harbor.k8s.lan
          notary: notary.harbor.k8s.lan
    core:
      replicas: 1
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    chartmuseum:
      replicas: 1
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    jobservice:
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    notary:
      enabled: false
    portal:
      replicas: 1
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    registry:
      replicas: 1
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    trivy:
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    database:
      type: external
      external:
        host: postgresql
        port: 5432
        username: harbor
        password: hYkQD4KsG-wSf4jAN0MGQx5YjsqLVHNn
        coreDatabase: harbor-registry
        notaryServerDatabase: harbor-notaryserver
        notarySignerDatabase: harbor-notarysigner
    redis:
      type: internal
  interval: 1m
  install:
    remediation:
      retries: 3
