apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-chartmuseum-rwx
  namespace: smol-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice-rwx
  namespace: smol-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-rwx
  namespace: smol-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
