apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: harbor-redis
  namespace: default
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor-redis
  namespace: default
spec:
  releaseName: harbor-redis-ha
  targetNamespace: smol-system
  chart:
    spec:
      chart: redis
      version: ">=17.0.0 <17.1.0"
      sourceRef:
        kind: HelmRepository
        name: harbor-redis
  values:
    auth:
      enabled: false
      sentinel: false
    sentinel:
      enabled: true
      masterSet: harbor
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
      priorityClassName: harbor-redis
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    replica:
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: rook-ceph-tools
      priorityClassName: harbor-redis
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
  interval: 1m
  install:
    remediation:
      retries: 3
