---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Role
metadata:
  name: harbor
spec:
  forProvider:
    connectionLimit: 50
    privileges:
      login: true
    passwordSecretRef:
      name: postgres-harbor-connection
      namespace: smol-system
      key: password
  writeConnectionSecretToRef:
    name: postgres-harbor-role-secret
    namespace: smol-system
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: harbor-registry
spec:
  forProvider: {}
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: harbor-notaryserver
spec:
  forProvider: {}
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: harbor-notarysigner
spec:
  forProvider: {}
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: harbor-registry
spec:
  forProvider:
    privileges:
      - CONNECT
      - TEMPORARY
    roleRef:
      name: harbor
    databaseRef:
      name: harbor-registry
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: harbor-notaryserver
spec:
  forProvider:
    privileges:
      - CONNECT
      - TEMPORARY
    roleRef:
      name: harbor
    databaseRef:
      name: harbor-notaryserver
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: harbor-notarysigner
spec:
  forProvider:
    privileges:
      - CONNECT
      - TEMPORARY
    roleRef:
      name: harbor
    databaseRef:
      name: harbor-notarysigner
