apiVersion: v1
kind: LimitRange
metadata:
  name: smol-devtools
  namespace: smol-devtools
spec:
  limits:
  - default:
      cpu: 1
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container
