---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: smol-devtools
  name: smol-devtools

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: smol-devtools
  name: smol-devtools
  namespace: smol-devtools

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: smol-devtools
  name: smol-devtools-reconciler
  namespace: smol-devtools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:smol-devtools:reconciler
- kind: ServiceAccount
  name: smol-devtools
  namespace: smol-devtools

