---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: syncthing
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./deploy/syncthing
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  validation: client

