apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: elastic
spec:
  interval: 5m
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
spec:
  releaseName: elastic-operator
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
  interval: 1m
  install:
    remediation:
      retries: 3
