apiVersion: v1
kind: Namespace
metadata:
  name: percona
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: percona
spec:
  interval: 5m
  url: https://percona.github.io/percona-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pxc-operator
spec:
  releaseName: pxc-operator
  targetNamespace: percona
  chart:
    spec:
      chart: pxc-operator
      sourceRef:
        kind: HelmRepository
        name: percona
  interval: 1m
  install:
    remediation:
      retries: 3

