apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controller
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
spec:
  interval: 5m
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  targetNamespace: ingress-controller
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    deployment:
      annotations:
        prometheus.io/scrape: true
