apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patchesStrategicMerge:
- helm-controller.yaml
- notification-controller.yaml
- kustomize-controller-patch.yaml
- source-controller-patch.yaml
