apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubereboot
  namespace: default
spec:
  interval: 5m
  url: https://kubereboot.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: default
spec:
  releaseName: kured
  targetNamespace: smol-system
  chart:
    spec:
      chart: kured
      version: ">=2.11.0 <2.12.0"
      sourceRef:
        kind: HelmRepository
        name: kubereboot
  values:
    priorityClassName: smol-additional
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  interval: 1m
  install:
    remediation:
      retries: 3
