apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kured
spec:
  interval: 5m
  url: https://weaveworks.github.io/kured
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
spec:
  releaseName: kured
  targetNamespace: kube-system
  chart:
    spec:
      chart: kured
      sourceRef:
        kind: HelmRepository
        name: kured
  interval: 1m
  install:
    remediation:
      retries: 3
