apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubereboot
  namespace: smol-gitops
spec:
  interval: 5m
  url: https://kubereboot.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: smol-gitops
spec:
  releaseName: kured
  targetNamespace: kube-system
  chart:
    spec:
      chart: kured
      version: ">=4.0.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: smol-gitops
  values:
    image:
      tag: 1.9.2
    priorityClassName: system-node-critical
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  interval: 1m
  install:
    remediation:
      retries: 3
