apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kured
  namespace: default
spec:
  interval: 5m
  url: https://weaveworks.github.io/kured
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: default
spec:
  releaseName: kured
  targetNamespace: smol-system
  chart:
    spec:
      chart: kured
      version: ">=2.11.0 <2.12.0"
      sourceRef:
        kind: HelmRepository
        name: kured
  values:
    priorityClassName: smol-additional
  interval: 1m
  install:
    remediation:
      retries: 3
