apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controller
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: contour
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
spec:
  releaseName: contour
  targetNamespace: ingress-controller
  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: contour
  interval: 1m
  install:
    remediation:
      retries: 3
