apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: haproxytech
  namespace: default
spec:
  interval: 5m
  url: https://haproxytech.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: default
spec:
  releaseName: haproxy
  targetNamespace: smol-system
  chart:
    spec:
      chart: kubernetes-ingress
      version: ">=1.21.0 <1.22.0"
      sourceRef:
        kind: HelmRepository
        name: haproxytech
  values:
    controller:
      kind: DaemonSet
      unprivileged: false
      ingressClassResource:
        name: haproxy
        default: true
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.10.0
      PodDisruptionBudget:
        enable: true
      priorityClassName: smol-critical
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
    defaultBackend:
      enabled: false
  interval: 1m
  install:
    remediation:
      retries: 3
