apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controller
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: haproxytech
spec:
  interval: 5m
  url: https://haproxytech.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
spec:
  releaseName: haproxy
  targetNamespace: ingress-controller
  chart:
    spec:
      chart: kubernetes-ingress
      sourceRef:
        kind: HelmRepository
        name: haproxytech
  values:
    controller:
      kind: DaemonSet
      unprivileged: false
      ingressClassResource:
        enabled: true
        default: true
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.10.0
      PodDisruptionBudget:
        enable: true
  interval: 1m
  install:
    remediation:
      retries: 3
