apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubernetes-secret-generator
  namespace: smol-gitops
spec:
  interval: 5m
  url: https://helm.mittwald.de
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-generator
  namespace: smol-gitops
spec:
  releaseName: secret-generator
  targetNamespace: smol-gitops
  chart:
    spec:
      chart: kubernetes-secret-generator
      sourceRef:
        kind: HelmRepository
        name: kubernetes-secret-generator
  values:
    priorityClassName: smol-gitops
    tolerations:
      - key: "node-role.kubernetes.io/storage"
        operator: Exists
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: smol.k8s.lan/manager
                  operator: In
                  values:
                    - prefer
  interval: 1m
  install:
    remediation:
      retries: 3
