apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: memcached
  namespace: default
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: memcached
  namespace: default
spec:
  releaseName: memcached
  targetNamespace: smol-system
  chart:
    spec:
      chart: memcached
      version: ">=6.0.0 <6.1.0"
      sourceRef:
        kind: HelmRepository
        name: memcached
  values:
    priorityClassName: smol-system
  interval: 1m
  install:
    remediation:
      retries: 3
