---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: smol-network
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: smol-network
spec:
  releaseName: metallb
  targetNamespace: smol-network
  chart:
    spec:
      chart: metallb
      version: ">=4.1.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: smol-network
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    controller:
      priorityClassName: loadbalancer
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      tolerations:
        - key: node-role.kubernetes.io/storage
          operator: Exists
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: smol.k8s.lan/manager
                    operator: In
                    values:
                      - prefer
    speaker:
      priorityClassName: smol-network
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    configInline:
      peers:
        - peer-address: 192.168.1.1
          peer-asn: 64512
          my-asn: 64513
      address-pools:
        - name: default
          protocol: bgp
          addresses:
            - 192.168.10.0/24
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  creationTimestamp: null
  name: peer1
  namespace: smol-network
spec:
  holdTime: 1m30s
  keepaliveTime: 0s
  myASN: 64513
  passwordSecret: {}
  peerASN: 64512
  peerAddress: 192.168.1.1
status: {}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: default
  namespace: smol-network
spec:
  addresses:
    - 192.168.10.0/24
status: {}
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  creationTimestamp: null
  name: bgpadvertisement1
  namespace: smol-network
spec:
  ipAddressPools:
    - default
status: {}
---

