apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: ceph-fs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 2
    failureDomain: host
  dataPools:
    - replicated:
        size: 2
      failureDomain: osd
  preservePoolsOnDelete: false
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 3
    activeStandby: false
    priorityClassName: rook-ceph
    livenessProbe:
      disabled: true
      probe:
        timeoutSeconds: 120
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "8Gi"
    placement:
      tolerations:
      - key: node-role.kubernetes.io/storage
        operator: Exists
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: smol.k8s.lan/storage
              operator: In
              values:
              - prefer
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: rook-ceph-mds
