apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: ceph-fs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 2
    failureDomain: host
  dataPools:
    - replicated:
        size: 2
      failureDomain: osd
  preservePoolsOnDelete: false
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
    resources:
      requests:
        cpu: "1"
        memory: "1024Mi"
