---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: ceph-objectstore
value: 999999000
globalDefault: false
description: "This priority class should be used for rook-ceph pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: ceph-filesystem
value: 999999000
globalDefault: false
description: "This priority class should be used for rook-ceph pods only."
