apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-objectstore
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
   objectStoreName: my-store
   objectStoreNamespace: rook-ceph
