apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: main
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
  dataPool:
    failureDomain: osd
    replicated:
      size: 2
  gateway:
    port: 80
    securePort: 443
    instances: 3
