apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: main
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
  dataPool:
    failureDomain: osd
    replicated:
      size: 2
  gateway:
    port: 80
    instances: 2
    priorityClassName: rook-ceph
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "250m"
        memory: "512Mi"
    placement:
      tolerations:
      - key: node-role.kubernetes.io/storage
        operator: Exists
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - ceph-rgw
            topologyKey: "kubernetes.io/hostname"
