apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: main
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
  dataPool:
    failureDomain: osd
    replicated:
      size: 2
  gateway:
    port: 80
    instances: 4
    priorityClassName: rook-ceph
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "250m"
        memory: "512Mi"
    placement:
      tolerations:
      - key: node-role.kubernetes.io/storage
        operator: Exists
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: smol.k8s.lan/storage
              operator: In
              values:
              - prefer
        topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: rook-ceph-rgw
