#################################################################################################################
# Define the settings for the rook-ceph cluster with common settings for a small test cluster.
# All nodes with available raw devices will be used for the Ceph cluster. One node is sufficient
# in this example.

# For example, to create the cluster:
#   kubectl create -f crds.yaml -f common.yaml -f operator.yaml
#   kubectl create -f cluster-test.yaml
#################################################################################################################
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph # namespace:cluster
data:
  config: |
    [global]
    osd_pool_default_size = 2
    mon_warn_on_pool_no_redundancy = true
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: main-cluster
  namespace: rook-ceph # namespace:cluster
spec:
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: ceph/ceph:v16.2.5
    allowUnsupported: true
  mon:
    count: 3
    allowMultiplePerNode: false
  resources:
    api:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    mgr:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    mon:
      requests:
        cpu: "1000m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    osd:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
  priorityClassNames:
    all: rook-ceph
  dashboard:
    enabled: false
  crashCollector:
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 60s
        timeout: 600s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
    livenessProbe:
      mon:
        disabled: true
      mgr:
        disabled: true
      osd:
        disabled: true
  disruptionManagement:
    managePodBudgets: true
  monitoring:
    enabled: false
    rulesNamespace: "rook-ceph"
  removeOSDsIfOutAndSafeToRemove: true
