apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ceph-priorityclass.yaml
- ceph-cluster.yaml
- ceph-objectstore.yaml
- ceph-objectstore-ingress.yaml
- ceph-objectstore-user.yaml
- ceph-filesystem.yaml
- ceph-storageclass.yaml
