apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: chaos-mesh
  namespace: default
spec:
  interval: 5m
  url: https://charts.chaos-mesh.org
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: default
spec:
  releaseName: chaos-mesh
  targetNamespace: smol-system
  chart:
    spec:
      chart: chaos-mesh
      version: ">=2.2.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
  values:
    controllerManager:
      priorityClassName: smol-additional
      replicaCount: 2
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/component"
                  operator: In
                  values:
                    - controller-manager
              topologyKey: "kubernetes.io/hostname"
    chaosDaemon:
      priorityClassName: smol-additional
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
    dashboard:
      service:
        type: ClusterIP
      priorityClassName: smol-system
      replicaCount: 2
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/component"
                operator: In
                values:
                  - chaos-dashboard
            topologyKey: "kubernetes.io/hostname"
      ingress:
        enabled: true
        hosts:
          - name: chaos.k8s.lan
            paths: ["/"]
  interval: 1m
  install:
    remediation:
      retries: 3
