---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: chaos-mesh
  namespace: flux-system
spec:
  dependsOn:
  - name: smol
  interval: 1h0m0s
  path: ./deploy/chaos-mesh
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  validation: client
