---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: smol
  interval: 1h0m0s
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  validation: client
