---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-system
spec:
  dependsOn:
  - name: metallb
  interval: 1h0m0s
  path: ./deploy/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  validation: client

