---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./deploy/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  validation: client

