---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: postgresql
  namespace: flux-system
spec:
  dependsOn:
  - name: storage
  interval: 1h0m0s
  path: ./deploy/postgresql
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  validation: client
