---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook
  namespace: flux-system
spec:
  dependsOn:
  - name: monitoring
  interval: 1h0m0s
  path: ./deploy/rook
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  validation: client

