---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: media
  namespace: media
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: media-auth
  url: https://gitlab.com/kuft/media

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: media
  namespace: media
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: media
  sourceRef:
    kind: GitRepository
    name: media

