apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-tenant
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio
  namespace: default
spec:
  interval: 5m
  url: https://operator.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: default
spec:
  releaseName: minio-operator
  targetNamespace: minio-operator
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio
  interval: 1m
  install:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: default
spec:
  releaseName: minio-tenant
  targetNamespace: minio-tenant
  chart:
    spec:
      chart: tenant
      sourceRef:
        kind: HelmRepository
        name: minio
  values:
    tenants:
      - name: minio-1
        namespace: minio-tenant
        pools:
        - name: pool-0
          servers: 4
          pools: 1
          size: 128Gi
          StorageClassName: rook-ceph-fs-minio
  interval: 1m
  install:
    remediation:
      retries: 3
