apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rook
  namespace: default
spec:
  interval: 5m
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: default
spec:
  releaseName: rook-ceph
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: ">=1.8.0 <1.9.0"
      sourceRef:
        kind: HelmRepository
        name: rook
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    csi:
      enableCephfsSnapshotter: false
      enableRBDSnapshotter: false
      pluginpriorityClassName: smol-storage
      provisionerpriorityClassName: smol-storage
      pluginTolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      provisionerTolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
    tolerations:
      - key: "node-role.kubernetes.io/storage"
        operator: Exists
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
