apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rook
  namespace: default
spec:
  interval: 5m
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: default
spec:
  releaseName: rook-ceph
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: v1.8.1
    csi:
      enableCephfsSnapshotter: false
      enableRBDSnapshotter: false
      pluginPriorityClassName: rook-ceph
      provisionerPriorityClassName: rook-ceph
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
