apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rook
spec:
  interval: 5m
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  releaseName: rook-ceph
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: 1.5.7
      sourceRef:
        kind: HelmRepository
        name: rook
  interval: 1m
  install:
    remediation:
      retries: 3

