apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: default
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: default
spec:
  releaseName: metallb
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    configInline:
      peers:
      - peer-address: 192.168.1.1
        peer-asn: 64512
        my-asn: 64513
      address-pools:
      - name: default
        protocol: bgp
        addresses:
        - 192.168.10.0/24
