apiVersion: v1
kind: Namespace
metadata:
  name: syncthing
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-web
  namespace: syncthing
  labels:
    app: syncthing
spec:
  ports:
  - port: 8384
    name: web
  clusterIP: None
  selector:
    app: syncthing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: syncthing
spec:
  selector:
    matchLabels:
      app: syncthing
  replicas: 1
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: syncthing
        image: syncthing/syncthing
        ports:
        - containerPort: 8384
          name: web
        - containerPort: 22000
          name: sync
        - containerPort: 21027
          name: discovery
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: config
          mountPath: /var/syncthing/config
        - name: data
          mountPath: /var/syncthing/data
        - name: audiobooks
          mountPath: /var/syncthing/Audiobooks
        - name: music
          mountPath: /var/syncthing/Music
        - name: podcasts
          mountPath: /var/syncthing/Podcasts
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: syncthing-config
      - name: data
        persistentVolumeClaim:
          claimName: syncthing-data
      - name: audiobooks
        persistentVolumeClaim:
          claimName: audiobooks
      - name: music
        persistentVolumeClaim:
          claimName: music
      - name: podcasts
        persistentVolumeClaim:
          claimName: podcasts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: syncthing 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: syncthing 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks
  namespace: syncthing 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  namespace: syncthing 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcasts
  namespace: syncthing 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
