apiVersion: v1
kind: Namespace
metadata:
  name: syncthing
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
  labels:
    app: syncthing
spec:
  ports:
  - port: 8384
    name: web
  clusterIP: None
  selector:
    app: syncthing
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  namespace: syncthing
spec:
  selector:
    matchLabels:
      app: syncthing
  serviceName: syncthing
  replicas: 1
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: syncthing
        image: syncthing/syncthing
        ports:
        - containerPort: 8384
          name: web
        volumeMounts:
        - name: config
          mountPath: /var/syncthing/config
        - name: data
          mountPath: /var/syncthing/data
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
