apiVersion: v1
kind: Namespace
metadata:
  name: syncthing
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-web
  namespace: syncthing
  labels:
    app: syncthing
spec:
  ports:
  - port: 8384
    name: web
  clusterIP: None
  selector:
    app: syncthing
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-system
  namespace: syncthing
  labels:
    app: syncthing
spec:
  type: LoadBalancer
  ports:
  - port: 32000
    targetPort: 32000
    nodePort: 32000
    name: sync
  - port: 31027
    targetPort: 31027
    nodePort: 31027
    name: discovery
  selector:
    app: syncthing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: syncthing
spec:
  selector:
    matchLabels:
      app: syncthing
  replicas: 1
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: syncthing
        image: syncthing/syncthing
        ports:
        - containerPort: 8384
          name: web
        - containerPort: 32000
          name: sync
        - containerPort: 31027
          name: discovery
        volumeMounts:
        - name: config
          mountPath: /var/syncthing/config
        - name: data
          mountPath: /var/syncthing/data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: syncthing-config

      - name: data
        persistentVolumeClaim:
          claimName: syncthing-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: syncthing 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: syncthing 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
