apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  releaseName: postgresql
  targetNamespace: smol-system
  chart:
    spec:
      chart: postgresql
      version: ">=11.0.0 <12.0.0"
      sourceRef:
        kind: HelmRepository
        name: postgresql
  values:
    auth:
      existingSecret: postgresql
    primary:
      priorityClassName: smol-critical
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
      podAntiAffinityPreset: hard
      pdb:
        create: true
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists

      resources:
        requests:
          cpu: "250m"
          memory: "1Gi"
        limits:
          cpu: "250m"
          memory: "1Gi"
  interval: 1m
  install:
    remediation:
      retries: 3
