apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  releaseName: postgresql
  targetNamespace: smol-system
  chart:
    spec:
      chart: postgresql-ha
      sourceRef:
        kind: HelmRepository
        name: postgresql
  values:
    global:
      postgresql:
        existingSecret: postgresql
    postgresql:
      priorityClassName: smol-system
    pgpool:
      priorityClassName: smol-system
  interval: 1m
  install:
    remediation:
      retries: 3
