apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  releaseName: postgresql
  targetNamespace: smol-system
  chart:
    spec:
      chart: postgresql-ha
      version: ">=9.0.0 <10.0.0"
      sourceRef:
        kind: HelmRepository
        name: postgresql
  values:
    postgresql:
      replicaCount: 1
      priorityClassName: smol-system
      existingSecret: postgresql
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
      podAntiAffinityPreset: hard
      pdb:
        create: true
    pgpool:
      authenticationMethod: scram-sha-256
      extraEnvVars:
      - name: PGPOOL_ENABLE_POOL_HBA
        value: no
      logConnections: true
      replicaCount: 2
      priorityClassName: smol-system
      podAntiAffinityPreset: hard
      pdb:
        create: true
  interval: 1m
  install:
    remediation:
      retries: 3
