apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: postgresql
  namespace: smol-system
spec:
  forceRegenerate: false
  fields:
    - fieldName: postgresql-password
      encoding: base64url
      length: "32"
    - fieldName: repmgr-password
      encoding: base64url
      length: "32"
