apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: crossplane
  namespace: default
spec:
  interval: 5m
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: default
spec:
  releaseName: crossplane
  targetNamespace: smol-system
  chart:
    spec:
      chart: crossplane
      version: ">=1.6.0 <1.7.0"
      sourceRef:
        kind: HelmRepository
        name: crossplane
  values:
    tolerations:
      - key: "node-role.kubernetes.io/storage"
        operator: Exists
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: smol.k8s.lan/manager
              operator: In
              values:
              - prefer
    rbacManager:
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: smol.k8s.lan/manager
                operator: In
                values:
                - prefer
  interval: 1m
  install:
    remediation:
      retries: 3
