apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: crossplane
  namespace: default
spec:
  interval: 5m
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: default
spec:
  releaseName: crossplane
  targetNamespace: smol-system
  chart:
    spec:
      chart: crossplane
      version: ">=1.7.0 <1.8.0"
      sourceRef:
        kind: HelmRepository
        name: crossplane
  interval: 1m
  install:
    remediation:
      retries: 3
