apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: haproxytech
  namespace: smol-network
spec:
  interval: 5m
  url: https://haproxytech.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: smol-network
spec:
  releaseName: haproxy
  targetNamespace: smol-network
  chart:
    spec:
      chart: kubernetes-ingress
      version: ">=1.21.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: haproxytech
        namespace: smol-network
  values:
    controller:
      kind: DaemonSet
      unprivileged: true
      ingressClassResource:
        name: haproxy
        default: true
      service:
        type: LoadBalancer
      priorityClassName: ingress
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
      startupProbe:
        failureThreshold: 60
    defaultBackend:
      enabled: false
  interval: 1m
  install:
    remediation:
      retries: 3
