apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: default
spec:
  interval: 5m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: default
spec:
  releaseName: cert-manager
  targetNamespace: smol-system
  chart:
    spec:
      chart: cert-manager
      version: ">=1.8.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true
    tolerations:
      - key: "node-role.kubernetes.io/storage"
        operator: Exists
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: smol.k8s.lan/manager
              operator: In
              values:
              - prefer
    cainjector:
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: smol.k8s.lan/manager
                operator: In
                values:
                - prefer
    startupapicheck:
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: smol.k8s.lan/manager
                operator: In
                values:
                - prefer
    webhook:
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: smol.k8s.lan/manager
                operator: In
                values:
                - prefer
