apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  template:
    spec:
      priorityClassName: smol-critical
      containers:
        - name: manager
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
