apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - priorityclass.yaml
patchesStrategicMerge:
  - helm-controller-patch.yaml
  - notification-controller-patch.yaml
  - kustomize-controller-patch.yaml
  - source-controller-patch.yaml
  - image-automation-controller-patch.yaml
  - image-reflector-controller-patch.yaml
