apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      priorityClassName: smol-critical
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      containers:
        - name: manager
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
