apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
  annotations:
    kube-score/ignore: deployment-replicas, deployment-strategy
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: flux
    spec:
      priorityClassName: flux-system
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/part-of
                      operator: In
                      values:
                        - flux
                topologyKey: kubernetes.io/hostname
      containers:
        - name: manager
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 32Mi
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 32Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
