apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  template:
    spec:
      priorityClassName: smol-system
      containers:
        - name: manager
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
