apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      priorityClassName: smol-critical
      tolerations:
        - key: "node-role.kubernetes.io/storage"
          operator: Exists
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: smol.k8s.lan/manager
                operator: In
                values:
                - prefer
      containers:
        - name: manager
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
