apiVersion: v1
kind: Namespace
metadata:
  name: percona
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: percona
spec:
  interval: 5m
  url: https://percona.github.io/percona-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pxc-operator
spec:
  releaseName: pxc-operator
  targetNamespace: percona
  chart:
    spec:
      chart: pxc-operator
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: percona
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    watchAllNamespaces: true
    createCRD: true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - pxc-operator
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
