apiVersion: v1
kind: Namespace
metadata:
  name: smol-system
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: smol-critical
value: 1000000000
globalDefault: false
description: "This priority class should be used for critical service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: smol-system
value: 900000000
globalDefault: false
description: "This priority class should be used for critical service pods only."
