apiVersion: v1
kind: Namespace
metadata:
  name: smol-system
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: smol-critical
value: 1000000000
globalDefault: false
description: "This priority class should be used for critical service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: smol-system
value: 900000000
globalDefault: false
description: "This priority class should be used for critical service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: smol-additional
value: 800000000
globalDefault: false
description: "This priority class should be used for critical service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: smol-storage
value: 1000000000
globalDefault: false
description: "This priority class should be used for storage pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: smol-cluster
value: 999999999
globalDefault: false
description: "This priority class should be used for smol-cluster pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: smol-data
value: 999999000
globalDefault: false
description: "This priority class should be used for database pods only."
