apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubernetes-secret-generator
  namespace: default
spec:
  interval: 5m
  url: https://helm.mittwald.de
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-generator
  namespace: default
spec:
  releaseName: secret-generator
  targetNamespace: smol-system
  chart:
    spec:
      chart: kubernetes-secret-generator
      sourceRef:
        kind: HelmRepository
        name: kubernetes-secret-generator
  values: {}
  interval: 1m
  install:
    remediation:
      retries: 3
